logLevel = "WARNING"
InsecureSkipVerify = true # HTTPS Internal Server Error
[traefikLog]
  filePath = "/var/log/traefik.log"
[accessLog]
  filePath = "/var/log/access.log"

  [entryPoints.dashboard]
  address = "127.0.0.1:9999"

[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoints = ["https"]

  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/etc/traefik/ssl/fullchain.pem"
        keyFile = "/etc/traefik/ssl/privkey.pem"

      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
       ]

#defaultEntryPoints = ["http"]

[api]
entryPoint = "dashboard"
dashboard = true

[file]
directory = "/etc/traefik/rules/"
watch = true
